### ISSUE TITLE
how to deploy the backend to a prod environment？

### ISSUE THREAD

**Issue by radiorz** [ashleydavis/pnpm-workspace-examples#2]

**Comment by ashleydavis** [comment]
Put it in a Docker container.

**Comment by radiorz** [comment]
What I want to ask is how to get the dependencies like "validation":"workspace^",
because these libraries do not exist in the package in production. If possible please tell me how to pack a server package with node_modules and can run it immediately。

**Comment by ashleydavis** [comment]
You need to do a "pnpm install" in your Dockerfile. This will resolve the "workspace" dependencies.

Then do whatever you need to build your project. 

After that run `pnpm deploy`.

As an alternative, I created my own tool to flatten node_modules: https://www.npmjs.com/package/hoist-modules

Here are the relevant docs:
- https://pnpm.io/cli/deploy
- https://pnpm.io/docker
